### ISSUE TITLE
Join the Metis project

### ISSUE THREAD

**Issue by Kaympe20** [Kaympe20/Metis#2]
@thatonecoder I see you made the [Metis Revamped](https://modrinth.com/modpack/metis-revamped). Given your improvements, I would be extremely happy to have you on the main project. What do you say?

**Comment by Kaympe20** [comment]
@ThatOneCoder I do not appreciate your stealing of my logo and name. I gave you a generous offer and I am now filing a DMCA takedown of your page.

**Comment by ThatOneCoder** [comment]
Uh, I made my github account two years ago and haven't touched it once, I
am fourteen years old, so I am really sorry that this happened to you, but
I think you have the wrong person, as I haven't the slightest idea of how
to code, much less make a revamp of somebody else's code.

**Comment by Kaympe20** [comment]
I am so sorry I got you involved in this. [This is the person](https://modrinth.com/user/thatonecoder) I am looking for.
